name: Pages Build and Deploy
on:
  push:
    branches: [main]
  pull_request:

permissions: {}

jobs:
  build-and-deploy:
    name: generate and deploy
    strategy:
      matrix:
        conference: [heapcon25, gotechworld25, 040codersignite25, ndcmanchester25, ndcsecurity26, 040coders26, bsidesgrun26]
      max-parallel: 1  # Ensure jobs run sequentially to avoid GitHub Pages conflicts
    
    concurrency: ci-${{ github.ref }}-${{ matrix.conference }} # Recommended if you intend to make multiple deployments in quick succession.
    permissions:
      contents: write # requires to push generated slides
    
    runs-on: ubuntu-latest
    env:
      CONFERENCE: ${{ matrix.conference }}
    
    steps:
      - uses: actions/setup-node@v6.3.0
        with:
          node-version: 24

      - name: 🛎️ Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: 🔧 Install
        run: |
          npm ci
          
      - name: 🔧 Build pages for ${{ matrix.conference }}
        run: |
          npm run build:html

      - name: 🚀 Deploy ${{ matrix.conference }}
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f # v4.8.0
        with:
          branch: gh-pages
          folder: build-${{ matrix.conference }}
          target-folder: ${{ matrix.conference }}
